### ISSUE TITLE
Docker File Typo

### ISSUE THREAD

**Issue by TylerHillery** [jwills/buenavista#6]
I was having an issue with running the buenavista docker image because the "buneavista.backend" module did not exist. Looks like this is because of recent a commit  jwills@8d7855250132a549f117d82244c57450aa693013 renaming the backend module to backends.  

After I changed the CMD in the docker file from `python -m buenavista.backend.duckdb` to `python -m buenavista.backends.duckdb` everything worked.

I will open up a PR with the fix.

**Comment by jwills** [comment]
ack, thanks Tyler!
